version: '3.8'
services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: mounirbrm
      MONGO_INITDB_ROOT_PASSWORD: 223JMT2399
    ports:
      - 27017:27017
    volumes:
      - ./data/dump:/dump

  app:
    build: .
    image: localhost:8083/nodemongoapp:6.0
    restart: always
    container_name: back
    ports:
      - '3001:3001'
    depends_on:
      - db
volumes:
  mongo-data:
